/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as FieldTrackingRouteImport } from './routes/field-tracking'
import { Route as CompOffsRouteImport } from './routes/comp-offs'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AdvancesRouteImport } from './routes/advances'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldTrackingRoute = FieldTrackingRouteImport.update({
  id: '/field-tracking',
  path: '/field-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const CompOffsRoute = CompOffsRouteImport.update({
  id: '/comp-offs',
  path: '/comp-offs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancesRoute = AdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advances': typeof AdvancesRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/comp-offs': typeof CompOffsRoute
  '/field-tracking': typeof FieldTrackingRoute
  '/holidays': typeof HolidaysRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advances': typeof AdvancesRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/comp-offs': typeof CompOffsRoute
  '/field-tracking': typeof FieldTrackingRoute
  '/holidays': typeof HolidaysRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advances': typeof AdvancesRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/comp-offs': typeof CompOffsRoute
  '/field-tracking': typeof FieldTrackingRoute
  '/holidays': typeof HolidaysRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advances'
    | '/attendance'
    | '/calendar'
    | '/chat'
    | '/comp-offs'
    | '/field-tracking'
    | '/holidays'
    | '/leaves'
    | '/login'
    | '/meetings'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/shifts'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advances'
    | '/attendance'
    | '/calendar'
    | '/chat'
    | '/comp-offs'
    | '/field-tracking'
    | '/holidays'
    | '/leaves'
    | '/login'
    | '/meetings'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/shifts'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advances'
    | '/attendance'
    | '/calendar'
    | '/chat'
    | '/comp-offs'
    | '/field-tracking'
    | '/holidays'
    | '/leaves'
    | '/login'
    | '/meetings'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/shifts'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdvancesRoute: typeof AdvancesRoute
  AttendanceRoute: typeof AttendanceRoute
  CalendarRoute: typeof CalendarRoute
  ChatRoute: typeof ChatRoute
  CompOffsRoute: typeof CompOffsRoute
  FieldTrackingRoute: typeof FieldTrackingRoute
  HolidaysRoute: typeof HolidaysRoute
  LeavesRoute: typeof LeavesRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  PayrollRoute: typeof PayrollRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ShiftsRoute: typeof ShiftsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-tracking': {
      id: '/field-tracking'
      path: '/field-tracking'
      fullPath: '/field-tracking'
      preLoaderRoute: typeof FieldTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comp-offs': {
      id: '/comp-offs'
      path: '/comp-offs'
      fullPath: '/comp-offs'
      preLoaderRoute: typeof CompOffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advances': {
      id: '/advances'
      path: '/advances'
      fullPath: '/advances'
      preLoaderRoute: typeof AdvancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdvancesRoute: AdvancesRoute,
  AttendanceRoute: AttendanceRoute,
  CalendarRoute: CalendarRoute,
  ChatRoute: ChatRoute,
  CompOffsRoute: CompOffsRoute,
  FieldTrackingRoute: FieldTrackingRoute,
  HolidaysRoute: HolidaysRoute,
  LeavesRoute: LeavesRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  PayrollRoute: PayrollRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ShiftsRoute: ShiftsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
