/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'

declare let self: ServiceWorkerGlobalScope

cleanupOutdatedCaches()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Cache Large AI Models (CacheFirst - they don't change often)
registerRoute(
  ({ url }) => url.pathname.includes('/models/'),
  new CacheFirst({
    cacheName: 'face-api-models',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
)

// Cache Google Fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts',
  })
)

// Default NetworkFirst for API calls
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
  })
)

// Handle Push Notifications
self.addEventListener('push', (event) => {
  let title = 'New Message'
  let body = 'You have a new message.'
  let pushData: Record<string, unknown> = {}

  if (event.data) {
    try {
      const json = event.data.json()
      title = json.title || title
      body = json.body || body
      pushData = json.data || {}
    } catch {
      body = event.data.text()
    }
  }

  const isCall = pushData.type === 'call'

  const options = {
    body,
    icon: '/icon-192.png',
    badge: '/favicon.ico',
    vibrate: isCall ? [200, 100, 200, 100, 200, 100, 200] : [100, 50, 100],
    data: {
      url: pushData.url ? `${self.location.origin}${pushData.url}` : self.location.origin + '/chat',
      type: pushData.type || 'message',
      callerName: pushData.callerName,
      callerId: pushData.callerId,
      roomId: pushData.roomId,
    },
    tag: isCall ? `call-${pushData.roomId}` : undefined,
    renotify: isCall,
    requireInteraction: isCall,
    silent: !isCall,
    actions: isCall
      ? [
          { action: 'accept', title: 'Accept', icon: '/icon-192.png' },
          { action: 'reject', title: 'Decline', icon: '/favicon.ico' },
        ]
      : undefined,
  }

  event.waitUntil(
    self.registration.showNotification(title, options)
  )
})

// Handle notification click / action
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  if (event.action === 'reject') {
    return
  }

  const targetUrl = event.notification.data?.url || self.location.origin + '/chat'

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (let i = 0; i < clientList.length; i++) {
        const client = clientList[i]
        if (client.focused || client.visibilityState === 'visible') {
          client.navigate(targetUrl)
          return client.focus()
        }
      }
      return self.clients.openWindow(targetUrl)
    })
  )
})
